---
abstract: 'RT-Extension-Lumen Extension'
author:
  - 'Blaine Motsinger <blaine@renderorange.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
test_requires:
  Test::More: 0
  Test::CheckManifest: 0
  Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Lumen
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.001'
x_module_install_rtx_version: '0.43'
x_requires_rt: 6.0.0
x_rt_too_new: 6.1.0
